config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'
  get 'pages/home'
  get 'pages/about'

  resources :users
  resources :products do
    resources :orders
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
    @product = Product.find(params[:product_id])
  end

  def create
    service_fee = 5.0
    @product = Product.find(params[:product_id])
    @order = Order.new(
      product_id: @product.id,
      final_price: @product.price.to_f + service_fee
    )
    @order.save
    redirect_to product_order_path(@product.id, @order)
  end

  def show
    @order = Order.find(params[:id])
    @product = Product.find(@order.product_id)
  end

private

def order_params
  params.require(:order).permit()

end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new

  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to root_path
  end


private

def user_params
  params.require(:user).permit(:first_name, :last_name, :email)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asams</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/new.html.erb
<!-- <h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p> -->

Buy a <%= @product.name %>

<%= form_for([@product, @order]) do |f| %>

<%=  f.submit 'Complete Oeder' %>

<% end %>

app/views/orders/show.html.erb
<!-- <h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p> -->
<h1>Thanks for placing your order</h1>
<hr>
<h3>Your order will be ready in 30 min</h3>

<%= @product.name %> x1 .................$ <%= @product.price %><br>
Service fee ($5.00) .....................$ 5.00<br>
<hr>

$<%= @order.final_price %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<!-- <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p> -->
 <h1> Eat with ASAMS </h1>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<!-- <h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p> -->


<h1>Eat With ASAMS</h1>


<% @products.each do |p| %>
<div class="product">
  <h3><%= link_to "#{p.name}", p %></h3>
<h3><%= p.name %></h3>
<p>$<%= p.price %><br></p>
<p><%= p.description %></p>
</div>
<% end %>

app/views/products/new.html.erb
<!-- <h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p> -->

app/views/products/show.html.erb
<!-- <h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p> -->
<%= @product.name %><br>
<p>$<%= @product.price %></p>
<%= link_to 'Buy Now', new_product_order_path(@product) %> <br>
<p><%= @product.description %></P>

app/views/users/new.html.erb
<h1>Create an account</h1>
<%= form_for(@user) do |f| %>
<%= f.text_field :first_name, placeholder: 'First Name'%><br>
<%= f.text_field :last_name, placeholder: 'Last Name' %><br>
<%= f.email_field :email, placeholder: 'Email Address' %><br>
<%= f.submit 'Create Account' %>
<% end %>